
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jalgibdtkfpzncsdduxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbGdpYmR0a2Zwem5jc2RkdXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODQwOTgsImV4cCI6MjA1OTI2MDA5OH0.ubDFtyJx2NJyGzBAQXuO1DwwXZBzFsLUQja39NHlEaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
